### ISSUE TITLE
s1_agent_upgrade The example playbook uses wrong roles?

### ISSUE THREAD

**Issue by grendelson** [Sentinel-One/ansible_collection_s1agents#2]
The example playbook entries use s1_agent _install , instead of s1_agent_upgrade.  It isn't clear if this is a typo or by design.

**Comment by s1-nathangerhart** [comment]
That is a typo the readme for the s1_agent_upgrade package. The examples should use `s1_agent_upgrade` module.
Thanks for reporting it. We'll fix it for the next release.
