### ISSUE TITLE
si_agent_download uses lower case "linux" but  Support gave us -Linux

### ISSUE THREAD

**Issue by grendelson** [Sentinel-One/ansible_collection_s1agents#3]
'fileName', 'match', '^Signed-SentinelAgent[_-]linux')  IN agent_download role

but 'fileName', 'match', '^Signed-SentinelAgent[_-][lL]linux')  <this works for either upper  or Lower!

or make it case insensitive?
Thanks

**Comment by s1-nathangerhart** [comment]
It does appear that we occasionally change the casing on the name of the signed package. Thanks for the updated regex we will test it out and incorporate it into the next release.
