### ISSUE TITLE
Problem with Download S1Agent

### ISSUE THREAD

**Issue by AlexanderBurdenko** [Sentinel-One/ansible_collection_s1agents#6]
Hello,
I am using Ansible collection to instal sentinelOne agent:

azure-arm.ubuntu: TASK [sentinelone.s1agents.s1_agent_download : Get available SentinelOne agent packages] ***
    azure-arm.ubuntu: FAILED - RETRYING: [default -> localhost]: Get available SentinelOne agent packages (10 retries left).
    azure-arm.ubuntu: FAILED - RETRYING: [default -> localhost]: Get available SentinelOne agent packages (9 retries left).
    azure-arm.ubuntu: FAILED - RETRYING: [default -> localhost]: Get available SentinelOne agent packages (8 retries left).
    azure-arm.ubuntu: FAILED - RETRYING: [default -> localhost]: Get available SentinelOne agent packages (7 retries left).
    azure-arm.ubuntu: FAILED - RETRYING: [default -> localhost]: Get available SentinelOne agent packages (6 retries left).
    azure-arm.ubuntu: FAILED - RETRYING: [default -> localhost]: Get available SentinelOne agent packages (5 retries left).
    azure-arm.ubuntu: FAILED - RETRYING: [default -> localhost]: Get available SentinelOne agent packages (4 retries left).
    azure-arm.ubuntu: FAILED - RETRYING: [default -> localhost]: Get available SentinelOne agent packages (3 retries left).
    azure-arm.ubuntu: FAILED - RETRYING: [default -> localhost]: Get available SentinelOne agent packages (2 retries left).
    azure-arm.ubuntu: FAILED - RETRYING: [default -> localhost]: Get available SentinelOne agent packages (1 retries left).
    azure-arm.ubuntu: fatal: [default -> localhost]: FAILED! => {"attempts": 10, "changed": false, "connection": "close", "content_length": "[92](https://github.com/BY-Product-Development/plat-saasa-agent-ubuntu-image/actions/runs/8848445621/job/24298285919#step:10:93)", "content_security_policy": "default-src 'self' ; connect-src 'self' *.sentinelone.net cdn.pendo.io app.pendo.io *.pendo.io data.pendo.io *.scalyr.com *.storage.googleapis.com sentry.io *.sentry.io *.google-analytics.com *.gstatic.com unpkg.com cdn.auth0.com wss://*.sentinelone.net https://www.googletagmanager.com https://cdnjs.cloudflare.com https://dm64t97qsxvuz.cloudfront.net data: ; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.sentinelone.net cdn.pendo.io app.pendo.io pendo-io-static.storage.googleapis.com *.storage.googleapis.com data.pendo.io https://www.google-analytics.com https://www.googletagmanager.com/ https://unpkg.com https://cdnjs.cloudflare.com/ https://dm64t97qsxvuz.cloudfront.net/ ; img-src 'self' *.sentinelone.net *.sentinelone.com dm64t97qsxvuz.cloudfront.net data: https://www.google-analytics.com cdn.pendo.io app.pendo.io *.storage.googleapis.com data.pendo.io ; style-src 'self' 'unsafe-inline' *.sentinelone.net app.pendo.io cdn.pendo.io *.storage.googleapis.com https://cdnjs.cloudflare.com/ https://dm64t97qsxvuz.cloudfront.net/ ; font-src 'self' data: *.sentinelone.net https://cdn.auth0.com https://dm64t97qsxvuz.cloudfront.net ; manifest-src 'self' https://dm64t97qsxvuz.cloudfront.net ; frame-src 'self' blob: https://receptive.io https://*.pendo.io https://pendo-io-extensions.storage.googleapis.com/ https://*.youtube.com *.sentinelone.net *.scalyr.com; frame-ancestors 'self' app.pendo.io *.sentinelone.net; object-src 'none'", "content_type": "application/octet-stream", "date": "Fri, 26 Apr 2024 12:46:27 GMT", "elapsed": 0, "msg": "Status code was 400 and not [200]: HTTP Error 400: Bad Request", "redirected": false, "server": "nginx", "status": 400, "strict_transport_security": "max-age=31536000; includeSubDomains", "url": "https://URL?limit=100&sortBy=version&sortOrder=desc&platformTypes=linux,windows&status=ga&version=23.3.2.12", "x_content_type_options": "nosniff", "x_frame_options": "SAMEORIGIN"}
    azure-arm.ubuntu:
    azure-arm.ubuntu: NO MORE HOSTS LEFT *************************************************************

What the problem ?

**Comment by s1-nathangerhart** [comment]
Hi @AlexanderBurdenko,

I tried to reproduce your issue and so far I am unable to. 
The the URL that was reported in the tasks output is valid, `"url": "https://URL?limit=100&sortBy=version&sortOrder=desc&platformTypes=linux,windows&status=ga&version=23.3.2.12"`, once we replace `URL` with a valid hostname for the console. There is no need to include the port number. 

I'd recommend checking the following items:

- If your console has ACLs configured, check that this host is on the allowed list
- Verify that the API token is still valid
- Test the URL directly with curl, you'll need to add an authorization header like so `curl -H "Authorization: Bearer <your api token> https://url...`

**Comment by AlexanderBurdenko** [comment]
I delete url and change it, but the problem that I can't download it, before this day it's work correct. I don't understand what changed
Token is correct

**Comment by s1-nathangerhart** [comment]
There haven't been any recent changes to the `s1_agent_download` role. If this used to work and now it doesn't, that points to it being something environmental, perhaps there is a recent changes to a perimeter firewall, proxy or similar device.

**Comment by AlexanderBurdenko** [comment]
> There haven't been any recent changes to the `s1_agent_download` role. If this used to work and now it doesn't, that points to it being something environmental, perhaps there is a recent changes to a perimeter firewall, proxy or similar device.

Hello
Thank you for answer, i guess i will check and delete the port 443. Maybe it help

**Comment by AlexanderBurdenko** [comment]
Hello
I have delete this port and now it's work. Strange situation, because previously it worked
